# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6lZZSdLZC48Hh5h4RCzVTeSLpTmAzsR
"""

def convert(status):
  if status == 'OK':
    return 0
  if status == 'ERR':
    return 1

import pandas as pd

df = pd.read_csv('/mnt/uart_dataset.csv',header=None)

df.columns = ['timestamp', 'status', 'sent', 'length', 'baudrate']

df['error'] = df['status'].apply(convert)

x = df[['length', 'baudrate']]
y = df['error']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size = 0.2,
    random_state = 0
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

print("훈련 끝")

def predict_error(length, baudrate):
  data = [[length, baudrate]]
  error_prob = model.predict_proba(data)[0][1]
  return error_prob

print(predict_error(10, 9600))

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

# OK 파란색
ok = df[df['error'] == 0]
plt.scatter(ok['length'], ok['baudrate'], c='blue', alpha=0.3, label='OK')

# ERR 빨간색
err = df[df['error'] == 1]
plt.scatter(err['length'], err['baudrate'], c='red', label='ERR')

plt.xlabel("Cable Length (m)")
plt.ylabel("Baudrate")
plt.title("Actual UART Measurements (Blue=OK, Red=ERR)")
plt.grid(True)
plt.legend()
plt.show()

baud_candidates = [9600, 19200, 38400, 57600, 115200, 230400]

def recommend_baudrate(length):
    best_baud = None
    best_prob = 9999

    for b in baud_candidates:
        p = predict_error(length, b)
        if p < best_prob:
            best_prob = p
            best_baud = b

    return best_baud, best_prob


def recommend_length(baudrate, threshold=0.01):
    best_length = 0
    for i in range(1, 61):
        length = i * 0.5
        p = predict_error(length, baudrate)
        print(f"Length: {length}m, Error Prob: {p:.6f}")
        if p < threshold:
            best_length = length
        else:
            break
    return best_length

def recommend(length=None, baudrate=None):
    if length is not None:
        b, prob = recommend_baudrate(length)
        return {
            "input_length": length,
            "recommended_baudrate": b,
            "error_probability": prob
        }

    if baudrate is not None:
        max_len = recommend_length(baudrate)
        return {
            "input_baudrate": baudrate,
            "max_stable_length": max_len
        }

    return "length 또는 baudrate 중 하나를 넣어야 합니다."

print(recommend(baudrate = 230400))
